commerce_payment.commerce_payment_gateway.plugin.spectrocoin:
  type: commerce_payment_gateway_configuration
  mapping:
    checkout_display:
      type: string
      label: "Checkout Display"
    project_id:
      type: string
      label: "User ID"
    client_id:
      type: string
      label: "Client ID"
    client_secret:
      type: string
      label: "Client Secret"
