name: Create tag and release

on:
  workflow_run:
    workflows: ["Launch release.yml after closed PR"]
    types:
      - completed
  workflow_dispatch:

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Fetch Latest PR Info and Check for Existing Tag
        id: check_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the latest merged PR title and body using GitHub CLI
          PR_TITLE=$(gh pr list --state merged --limit 1 --json title --jq '.[0].title')
          PR_BODY=$(gh pr list --state merged --limit 1 --json body --jq '.[0].body')
          TAG_NAME=$(echo "$PR_TITLE" | sed 's/ /_/g') # Replace spaces with underscores in the tag name for consistency

          # Check if the tag already exists
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag '$TAG_NAME' already exists. Exiting workflow."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
            exit 0
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
            echo "PR_TITLE: $PR_TITLE"
            echo "PR_BODY: $PR_BODY"
            echo "TAG_NAME: $TAG_NAME"

            # Create the tag
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"

            # Store the tag name for use in the next steps
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          fi

      - name: Create Release
        if: env.TAG_EXISTS == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "Release ${{ env.TAG_NAME }}"
          body: "Automated release created by GitHub Actions."
          draft: false
          prerelease: false

      - name: Prepare module directory and create zip file
        if: env.TAG_EXISTS == 'false'
        run: |
          MODULE_NAME="commerce_spectrocoin"
          TAG_NAME=${{ env.TAG_NAME }}

          # Create the module directory
          mkdir -p build/$MODULE_NAME

          # Move all source files into the module directory
          rsync -av --exclude='build' --exclude='.git*' --exclude='.github*' --exclude='.vscode*' --exclude='*.md' --exclude='.gitignore' ./ build/$MODULE_NAME

          # Change to the build directory and create the zip file with the tag name appended
          cd build
          ZIP_FILE_NAME="../${MODULE_NAME}_${TAG_NAME}.zip"
          zip -r "$ZIP_FILE_NAME" "$MODULE_NAME"

          # Return to the root directory
          cd ..

          # Print the ZIP file name
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Upload release asset
        if: env.TAG_EXISTS == 'false'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_FILE_NAME }}
          asset_name: ${{ env.ZIP_FILE_NAME }}
          asset_content_type: application/zip
